# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - target-branch: 'maintenance/v1.x'
    package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '01:00'
      timezone: America/Los_Angeles
    labels:
      - 'automerge'
    commit-message:
      prefix: 'chore:'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '01:00'
      timezone: America/Los_Angeles
    labels:
      - 'automerge'
