pull_request_rules:
  - name: Add community label to outside contributions
    conditions:
      - author≠@core-contributors
      - author≠@spl-maintainers
      - author≠@spl-triage
      - author≠@spl-write
      - author≠mergify[bot]
      - author≠dependabot[bot]
      - author≠github-actions[bot]
    actions:
      label:
        add:
          - community
  - name: Request review of community contributions from community PR subscribers
    conditions:
      - author≠@core-contributors
      - author≠@spl-maintainers
      - author≠@spl-triage
      - author≠@spl-write
      - author≠mergify[bot]
      - author≠dependabot[bot]
      - author≠github-actions[bot]
      # Only request reviews from the PR subscribers group if no one
      # has reviewed the community PR yet. These checks only match
      # reviewers with admin, write or maintain permission on the repository.
      - '#approved-reviews-by=0'
      - '#commented-reviews-by=0'
      - '#changes-requested-reviews-by=0'
      - '#review-requested=0'
    actions:
      request_reviews:
        teams:
          - '@solana-labs/community-pr-subscribers'
  - name: Automatic merge (squash) on CI success
    conditions:
      - and:
          - or:
              - and:
                  - base=maintenance/v1.x
                  - and:
                      - status-success=build-and-test
                      - status-success="Validate commit message"
              - and:
                  - base!=maintenance/v1.x
                  - status-success=all-web3-checks
          - label=automerge
          - label!=no-automerge
    actions:
      merge:
        method: squash
  - name: Remove automerge label on CI failure
    conditions:
      - label=automerge
      - '#status-failure!=0'
    actions:
      label:
        remove:
          - automerge
      comment:
        message: Automerge label removed due to a CI failure

commands_restrictions:
  # The author of copied PRs is the Mergify user.
  # Restrict `copy` access to Core Contributors
  copy:
    conditions:
      - author=@core-contributors
