name: Compile GitHub Pages
description: Compiles content for GitHub Pages and uploads it to the artifact cache

runs:
  using: composite
  steps:
    - name: Compile docs
      shell: bash
      run: pnpm compile:docs

    - name: Assemble Deploy Directory
      shell: bash
      run: |
        mkdir -p .ghpages-deploy
        cp -r ./doc/* .ghpages-deploy

    - name: Assemble Deploy Versioned Subdirectory
      shell: bash
      run: |
        mkdir -p .ghpages-deploy/v1.x
        cp -r ./doc/* .ghpages-deploy/v1.x

    - uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        name: ghpages-deploy-artifacts-v1-docs
        path: .ghpages-deploy
        retention-days: 1
