name: Lint, Build, and Test
description: Generates type definitions, bundles the code, runs all tests, and enforces code style.

runs:
  using: composite
  steps:
    - name: Enforce Code Formatting
      shell: bash
      run: pnpm --filter @solana/web3.js run test:prettier

    - name: Compile Types
      shell: bash
      run: pnpm --filter @solana/web3.js run compile:typedefs

    - name: Enforce Lint
      shell: bash
      run: pnpm --filter @solana/web3.js run test:lint

    - name: Compile JavaScript
      shell: bash
      run: pnpm --filter @solana/web3.js run compile:js

    - name: Smoke-test built bundles
      shell: bash
      run: pnpm --filter @solana/web3.js run test:smoke

    - name: Run Unit Tests
      shell: bash
      run: pnpm --filter @solana/web3.js run test:unit

    - name: Run Integration Tests
      shell: bash
      run: pnpm test:live
